version: "3"

services:
  db:
    restart: always
    image: postgres:12
    container_name: trello_sync_db
    environment:
      - POSTGRES_USER=trello_db
      - POSTGRES_PASSWORD=trello_db
      - POSTGRES_DB=trello_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      webnet:
        aliases:
          - trello_sync_db

  web:
    build: .
    working_dir: /TreloSinc
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: TreloSinc
    volumes:
      - .:/TreloSinc
    ports:
      - "8000:8000"
    networks:
      webnet:
        aliases:
          - trello_sync_app

volumes:
  data:

networks:
  webnet: